// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: foo.proto
#ifndef GRPC_foo_2eproto__INCLUDED
#define GRPC_foo_2eproto__INCLUDED

#include "foo.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace MultiService {

class Foo1Service final {
 public:
  static constexpr char const* service_full_name() {
    return "MultiService.Foo1Service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::MultiService::FooResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MultiService::FooResponse>> AsyncFoo(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MultiService::FooResponse>>(AsyncFooRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MultiService::FooResponse>> PrepareAsyncFoo(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MultiService::FooResponse>>(PrepareAsyncFooRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MultiService::FooResponse>* AsyncFooRaw(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MultiService::FooResponse>* PrepareAsyncFooRaw(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::MultiService::FooResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MultiService::FooResponse>> AsyncFoo(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MultiService::FooResponse>>(AsyncFooRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MultiService::FooResponse>> PrepareAsyncFoo(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MultiService::FooResponse>>(PrepareAsyncFooRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::MultiService::FooResponse>* AsyncFooRaw(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MultiService::FooResponse>* PrepareAsyncFooRaw(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Foo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Foo(::grpc::ServerContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Foo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Foo(::grpc::ServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFoo(::grpc::ServerContext* context, ::MultiService::FooRequest* request, ::grpc::ServerAsyncResponseWriter< ::MultiService::FooResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Foo<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Foo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::MultiService::FooRequest, ::MultiService::FooResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response) { return this->Foo(context, request, response); }));}
    void SetMessageAllocatorFor_Foo(
        ::grpc::experimental::MessageAllocator< ::MultiService::FooRequest, ::MultiService::FooResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::MultiService::FooRequest, ::MultiService::FooResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Foo(::grpc::ServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Foo(
      ::grpc::CallbackServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Foo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Foo<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Foo<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Foo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Foo(::grpc::ServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Foo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Foo(::grpc::ServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFoo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Foo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Foo(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Foo(::grpc::ServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Foo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Foo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Foo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::MultiService::FooRequest, ::MultiService::FooResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::MultiService::FooRequest, ::MultiService::FooResponse>* streamer) {
                       return this->StreamedFoo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Foo(::grpc::ServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFoo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MultiService::FooRequest,::MultiService::FooResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Foo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Foo<Service > StreamedService;
};

class Foo2Service final {
 public:
  static constexpr char const* service_full_name() {
    return "MultiService.Foo2Service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::MultiService::FooResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MultiService::FooResponse>> AsyncFoo(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MultiService::FooResponse>>(AsyncFooRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MultiService::FooResponse>> PrepareAsyncFoo(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MultiService::FooResponse>>(PrepareAsyncFooRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MultiService::FooResponse>* AsyncFooRaw(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MultiService::FooResponse>* PrepareAsyncFooRaw(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::MultiService::FooResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MultiService::FooResponse>> AsyncFoo(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MultiService::FooResponse>>(AsyncFooRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MultiService::FooResponse>> PrepareAsyncFoo(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MultiService::FooResponse>>(PrepareAsyncFooRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Foo(::grpc::ClientContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::MultiService::FooResponse>* AsyncFooRaw(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MultiService::FooResponse>* PrepareAsyncFooRaw(::grpc::ClientContext* context, const ::MultiService::FooRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Foo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Foo(::grpc::ServerContext* context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Foo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Foo(::grpc::ServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFoo(::grpc::ServerContext* context, ::MultiService::FooRequest* request, ::grpc::ServerAsyncResponseWriter< ::MultiService::FooResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Foo<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Foo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::MultiService::FooRequest, ::MultiService::FooResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::MultiService::FooRequest* request, ::MultiService::FooResponse* response) { return this->Foo(context, request, response); }));}
    void SetMessageAllocatorFor_Foo(
        ::grpc::experimental::MessageAllocator< ::MultiService::FooRequest, ::MultiService::FooResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::MultiService::FooRequest, ::MultiService::FooResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Foo(::grpc::ServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Foo(
      ::grpc::CallbackServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Foo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Foo<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Foo<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Foo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Foo(::grpc::ServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Foo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Foo(::grpc::ServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFoo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Foo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Foo(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Foo(::grpc::ServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Foo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Foo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Foo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::MultiService::FooRequest, ::MultiService::FooResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::MultiService::FooRequest, ::MultiService::FooResponse>* streamer) {
                       return this->StreamedFoo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Foo(::grpc::ServerContext* /*context*/, const ::MultiService::FooRequest* /*request*/, ::MultiService::FooResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFoo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MultiService::FooRequest,::MultiService::FooResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Foo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Foo<Service > StreamedService;
};

}  // namespace MultiService


#endif  // GRPC_foo_2eproto__INCLUDED
