// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: foo.proto
#ifndef GRPC_foo_2eproto__INCLUDED
#define GRPC_foo_2eproto__INCLUDED

#include "foo.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace basic {

class FooService final {
 public:
  static constexpr char const* service_full_name() {
    return "basic.FooService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status FooMethod(::grpc::ClientContext* context, const ::basic::FooRequest& request, ::basic::FooReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basic::FooReply>> AsyncFooMethod(::grpc::ClientContext* context, const ::basic::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basic::FooReply>>(AsyncFooMethodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basic::FooReply>> PrepareAsyncFooMethod(::grpc::ClientContext* context, const ::basic::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basic::FooReply>>(PrepareAsyncFooMethodRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void FooMethod(::grpc::ClientContext* context, const ::basic::FooRequest* request, ::basic::FooReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void FooMethod(::grpc::ClientContext* context, const ::basic::FooRequest* request, ::basic::FooReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void FooMethod(::grpc::ClientContext* context, const ::basic::FooRequest* request, ::basic::FooReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basic::FooReply>* AsyncFooMethodRaw(::grpc::ClientContext* context, const ::basic::FooRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basic::FooReply>* PrepareAsyncFooMethodRaw(::grpc::ClientContext* context, const ::basic::FooRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status FooMethod(::grpc::ClientContext* context, const ::basic::FooRequest& request, ::basic::FooReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basic::FooReply>> AsyncFooMethod(::grpc::ClientContext* context, const ::basic::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basic::FooReply>>(AsyncFooMethodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basic::FooReply>> PrepareAsyncFooMethod(::grpc::ClientContext* context, const ::basic::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basic::FooReply>>(PrepareAsyncFooMethodRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void FooMethod(::grpc::ClientContext* context, const ::basic::FooRequest* request, ::basic::FooReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void FooMethod(::grpc::ClientContext* context, const ::basic::FooRequest* request, ::basic::FooReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void FooMethod(::grpc::ClientContext* context, const ::basic::FooRequest* request, ::basic::FooReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::basic::FooReply>* AsyncFooMethodRaw(::grpc::ClientContext* context, const ::basic::FooRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basic::FooReply>* PrepareAsyncFooMethodRaw(::grpc::ClientContext* context, const ::basic::FooRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FooMethod_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status FooMethod(::grpc::ServerContext* context, const ::basic::FooRequest* request, ::basic::FooReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_FooMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FooMethod() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FooMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FooMethod(::grpc::ServerContext* /*context*/, const ::basic::FooRequest* /*request*/, ::basic::FooReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFooMethod(::grpc::ServerContext* context, ::basic::FooRequest* request, ::grpc::ServerAsyncResponseWriter< ::basic::FooReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FooMethod<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_FooMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_FooMethod() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::basic::FooRequest, ::basic::FooReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::basic::FooRequest* request, ::basic::FooReply* response) { return this->FooMethod(context, request, response); }));}
    void SetMessageAllocatorFor_FooMethod(
        ::grpc::experimental::MessageAllocator< ::basic::FooRequest, ::basic::FooReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::basic::FooRequest, ::basic::FooReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_FooMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FooMethod(::grpc::ServerContext* /*context*/, const ::basic::FooRequest* /*request*/, ::basic::FooReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* FooMethod(
      ::grpc::CallbackServerContext* /*context*/, const ::basic::FooRequest* /*request*/, ::basic::FooReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* FooMethod(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::basic::FooRequest* /*request*/, ::basic::FooReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_FooMethod<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_FooMethod<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_FooMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FooMethod() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FooMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FooMethod(::grpc::ServerContext* /*context*/, const ::basic::FooRequest* /*request*/, ::basic::FooReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_FooMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FooMethod() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_FooMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FooMethod(::grpc::ServerContext* /*context*/, const ::basic::FooRequest* /*request*/, ::basic::FooReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFooMethod(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_FooMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_FooMethod() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FooMethod(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_FooMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FooMethod(::grpc::ServerContext* /*context*/, const ::basic::FooRequest* /*request*/, ::basic::FooReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* FooMethod(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* FooMethod(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FooMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FooMethod() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::basic::FooRequest, ::basic::FooReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::basic::FooRequest, ::basic::FooReply>* streamer) {
                       return this->StreamedFooMethod(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FooMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FooMethod(::grpc::ServerContext* /*context*/, const ::basic::FooRequest* /*request*/, ::basic::FooReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFooMethod(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::basic::FooRequest,::basic::FooReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_FooMethod<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_FooMethod<Service > StreamedService;
};

}  // namespace basic


#endif  // GRPC_foo_2eproto__INCLUDED
