// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: foo.proto

#include "foo.pb.h"
#include "foo.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace basic {

static const char* FooService_method_names[] = {
  "/basic.FooService/FooMethod",
};

std::unique_ptr< FooService::Stub> FooService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FooService::Stub> stub(new FooService::Stub(channel));
  return stub;
}

FooService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_FooMethod_(FooService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FooService::Stub::FooMethod(::grpc::ClientContext* context, const ::basic::FooRequest& request, ::basic::FooReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::basic::FooRequest, ::basic::FooReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FooMethod_, context, request, response);
}

void FooService::Stub::experimental_async::FooMethod(::grpc::ClientContext* context, const ::basic::FooRequest* request, ::basic::FooReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::basic::FooRequest, ::basic::FooReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FooMethod_, context, request, response, std::move(f));
}

void FooService::Stub::experimental_async::FooMethod(::grpc::ClientContext* context, const ::basic::FooRequest* request, ::basic::FooReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FooMethod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::basic::FooReply>* FooService::Stub::PrepareAsyncFooMethodRaw(::grpc::ClientContext* context, const ::basic::FooRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::basic::FooReply, ::basic::FooRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FooMethod_, context, request);
}

::grpc::ClientAsyncResponseReader< ::basic::FooReply>* FooService::Stub::AsyncFooMethodRaw(::grpc::ClientContext* context, const ::basic::FooRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFooMethodRaw(context, request, cq);
  result->StartCall();
  return result;
}

FooService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FooService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FooService::Service, ::basic::FooRequest, ::basic::FooReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FooService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::basic::FooRequest* req,
             ::basic::FooReply* resp) {
               return service->FooMethod(ctx, req, resp);
             }, this)));
}

FooService::Service::~Service() {
}

::grpc::Status FooService::Service::FooMethod(::grpc::ServerContext* context, const ::basic::FooRequest* request, ::basic::FooReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace basic

