// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: foo.proto
#ifndef GRPC_foo_2eproto__INCLUDED
#define GRPC_foo_2eproto__INCLUDED

#include "foo.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace ServerStreamingRpc {

class FooService final {
 public:
  static constexpr char const* service_full_name() {
    return "ServerStreamingRpc.FooService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::ServerStreamingRpc::FooResponse>> GetFooList(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::ServerStreamingRpc::FooResponse>>(GetFooListRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ServerStreamingRpc::FooResponse>> AsyncGetFooList(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ServerStreamingRpc::FooResponse>>(AsyncGetFooListRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ServerStreamingRpc::FooResponse>> PrepareAsyncGetFooList(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ServerStreamingRpc::FooResponse>>(PrepareAsyncGetFooListRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetFooList(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest* request, ::grpc::ClientReadReactor< ::ServerStreamingRpc::FooResponse>* reactor) = 0;
      #else
      virtual void GetFooList(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest* request, ::grpc::experimental::ClientReadReactor< ::ServerStreamingRpc::FooResponse>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderInterface< ::ServerStreamingRpc::FooResponse>* GetFooListRaw(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::ServerStreamingRpc::FooResponse>* AsyncGetFooListRaw(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::ServerStreamingRpc::FooResponse>* PrepareAsyncGetFooListRaw(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::ServerStreamingRpc::FooResponse>> GetFooList(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::ServerStreamingRpc::FooResponse>>(GetFooListRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::ServerStreamingRpc::FooResponse>> AsyncGetFooList(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::ServerStreamingRpc::FooResponse>>(AsyncGetFooListRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::ServerStreamingRpc::FooResponse>> PrepareAsyncGetFooList(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::ServerStreamingRpc::FooResponse>>(PrepareAsyncGetFooListRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetFooList(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest* request, ::grpc::ClientReadReactor< ::ServerStreamingRpc::FooResponse>* reactor) override;
      #else
      void GetFooList(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest* request, ::grpc::experimental::ClientReadReactor< ::ServerStreamingRpc::FooResponse>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReader< ::ServerStreamingRpc::FooResponse>* GetFooListRaw(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest& request) override;
    ::grpc::ClientAsyncReader< ::ServerStreamingRpc::FooResponse>* AsyncGetFooListRaw(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::ServerStreamingRpc::FooResponse>* PrepareAsyncGetFooListRaw(::grpc::ClientContext* context, const ::ServerStreamingRpc::FooRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetFooList_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetFooList(::grpc::ServerContext* context, const ::ServerStreamingRpc::FooRequest* request, ::grpc::ServerWriter< ::ServerStreamingRpc::FooResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetFooList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetFooList() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetFooList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFooList(::grpc::ServerContext* /*context*/, const ::ServerStreamingRpc::FooRequest* /*request*/, ::grpc::ServerWriter< ::ServerStreamingRpc::FooResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFooList(::grpc::ServerContext* context, ::ServerStreamingRpc::FooRequest* request, ::grpc::ServerAsyncWriter< ::ServerStreamingRpc::FooResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetFooList<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetFooList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetFooList() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::ServerStreamingRpc::FooRequest, ::ServerStreamingRpc::FooResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::ServerStreamingRpc::FooRequest* request) { return this->GetFooList(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_GetFooList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFooList(::grpc::ServerContext* /*context*/, const ::ServerStreamingRpc::FooRequest* /*request*/, ::grpc::ServerWriter< ::ServerStreamingRpc::FooResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::ServerStreamingRpc::FooResponse>* GetFooList(
      ::grpc::CallbackServerContext* /*context*/, const ::ServerStreamingRpc::FooRequest* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::ServerStreamingRpc::FooResponse>* GetFooList(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::ServerStreamingRpc::FooRequest* /*request*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetFooList<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetFooList<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetFooList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetFooList() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetFooList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFooList(::grpc::ServerContext* /*context*/, const ::ServerStreamingRpc::FooRequest* /*request*/, ::grpc::ServerWriter< ::ServerStreamingRpc::FooResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetFooList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetFooList() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetFooList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFooList(::grpc::ServerContext* /*context*/, const ::ServerStreamingRpc::FooRequest* /*request*/, ::grpc::ServerWriter< ::ServerStreamingRpc::FooResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFooList(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetFooList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetFooList() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->GetFooList(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetFooList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFooList(::grpc::ServerContext* /*context*/, const ::ServerStreamingRpc::FooRequest* /*request*/, ::grpc::ServerWriter< ::ServerStreamingRpc::FooResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* GetFooList(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* GetFooList(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_GetFooList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_GetFooList() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::ServerStreamingRpc::FooRequest, ::ServerStreamingRpc::FooResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::ServerStreamingRpc::FooRequest, ::ServerStreamingRpc::FooResponse>* streamer) {
                       return this->StreamedGetFooList(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_GetFooList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetFooList(::grpc::ServerContext* /*context*/, const ::ServerStreamingRpc::FooRequest* /*request*/, ::grpc::ServerWriter< ::ServerStreamingRpc::FooResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedGetFooList(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::ServerStreamingRpc::FooRequest,::ServerStreamingRpc::FooResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_GetFooList<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_GetFooList<Service > StreamedService;
};

}  // namespace ServerStreamingRpc


#endif  // GRPC_foo_2eproto__INCLUDED
